# Generated by Django 5.0 on 2023-12-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
